export default defineEventHandler(() => {
  const links = ['/api/hello', '/api/wildcard/param', '/api/error']

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="/favicon.svg" />
  <title>Nitro Starter</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@exampledev/new.css@1.1.2/new.min.css">
</head>

<body>
  <header>
    <h1>🐣 Nitro Starter</h1>
  </header>
  <main>
    <h2>Endpoints</h2>
    <ul>
${links.map((link) => `<li><a href="${link}">${link}</a></li>`).join('\n')}
    </ul>
    <br>
    <hr>
    <footer>
      Generated by <a href="https://nitro.unjs.io/" target="_blank" rel="noopener">Nitro</a> at ${new Date().toUTCString()}
      |
      <a href="https://github.com/unjs/nitro" target="_blank" rel="noopener">GithHub</a>
    </footer>
  </main>
</body>
</html>
`.trimStart()
})
