name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - run: corepack enable

      # - run: cp .env.example .env

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build
        env:
          NITRO_PRESET: cloudflare

      - name: Deploy to Cloudflare
        run: npx wrangler publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
